spring.application.name=auth0
server.port=8081

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/Auth0
spring.datasource.username=postgres
spring.datasource.password=eshan
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Auth0 Configuration
auth0.audience=https://api.myshop.com
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://dev-x0wze358kxnl6nt7.us.auth0.com/
spring.security.oauth2.resourceserver.jwt.audiences=https://api.myshop.com
